services:
  db:
    restart: always
    image: postgres:latest
    container_name: avito-testtask
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tenders-bids
    ports:
      - 5432:5432
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d